"""
Script Name : build_catalog.py
Description : Source of truth for the ZIK song library. Defines 230
              royalty-free / public-domain focus tracks grouped by genre,
              then writes the validated payload to app/seeds/songs.json.

              Run with:
                  uv run python -m app.seeds.build_catalog

              Sources used (all royalty-free or public domain):
                - FreePD.com                  (CC0)
                - Incompetech / Kevin MacLeod (CC-BY 4.0)
                - YouTube Audio Library       (royalty-free)
                - Free Music Archive          (CC0 / CC-BY)
                - Pixabay Music               (royalty-free)

Author      : @tonybnya
"""

from __future__ import annotations

import json
from typing import Any

from app.config import Config


def _track(
    title: str,
    artist: str,
    genre: str,
    moods: list[str],
    bpm: int | None,
    external_url: str,
    cover_url: str | None = None,
    audio_path: str | None = None,
) -> dict[str, Any]:
    return {
        "title": title,
        "artist": artist,
        "genre": genre,
        "moods": moods,
        "bpm": bpm,
        "external_url": external_url,
        "cover_url": cover_url,
        "audio_path": audio_path,
    }


def get_audio_files(genre: str) -> list[str]:
    genre_dir = Config.AUDIO_DIR / genre
    if not genre_dir.exists():
        return []
    return sorted(
        f.name
        for f in genre_dir.iterdir()
        if f.suffix in (".mp3", ".wav") and f.is_file()
    )


# ---------------------------------------------------------------------------
# Lo-fi hip hop (50)
# ---------------------------------------------------------------------------
LOFI: list[dict[str, Any]] = [
    _track(
        "Midnight Coffee",
        "Chillhop Music",
        "lofi",
        ["focus", "calm", "study"],
        78,
        "https://www.youtube.com/watch?v=9P3oSw9M-2g",
    ),
    _track(
        "Lo-Fi Study Beat",
        "Lofi Girl",
        "lofi",
        ["focus", "study", "relaxing"],
        72,
        "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    ),
    _track(
        "Dreamscape",
        "Lo-Fi Beats",
        "lofi",
        ["dream", "atmospheric", "calm"],
        70,
        "https://www.youtube.com/watch?v=WPni755-Krg",
    ),
    _track(
        "Window Seat",
        "Pueblo Vista",
        "lofi",
        ["calm", "introspective", "warm"],
        75,
        "https://www.youtube.com/watch?v=8jPQjjsBbIc",
    ),
    _track(
        "Coffee Shop Vibes",
        "Dreamy",
        "lofi",
        ["focus", "calm", "peaceful"],
        80,
        "https://www.youtube.com/watch?v=lTRiuFIWV54",
    ),
    _track(
        "Lost in Pages",
        "Chillhop Music",
        "lofi",
        ["focus", "study", "introspective"],
        72,
        "https://www.youtube.com/watch?v=oPVteJElF4o",
    ),
    _track(
        "Rainy Day Reading",
        "Lofi Records",
        "lofi",
        ["calm", "study", "melancholy"],
        68,
        "https://www.youtube.com/watch?v=6gyP4LbXdyA",
    ),
    _track(
        "Late Night Code",
        "Lo-Fi Beats",
        "lofi",
        ["focus", "study", "deep"],
        74,
        "https://www.youtube.com/watch?v=M8bDpHXNcCQ",
    ),
    _track(
        "Slow Train",
        "Chillhop Music",
        "lofi",
        ["calm", "warm", "introspective"],
        76,
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    ),
    _track(
        "City Lights at Dusk",
        "Dreamy",
        "lofi",
        ["dream", "atmospheric", "calm"],
        70,
        "https://www.youtube.com/watch?v=rUxyKA_-grg",
    ),
    _track(
        "Vinyl Memories",
        "Lo-Fi Vibes",
        "lofi",
        ["warm", "introspective", "calm"],
        80,
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    ),
    _track(
        "Saturday Morning",
        "Lofi Records",
        "lofi",
        ["bright", "focus", "uplifting"],
        82,
        "https://www.youtube.com/watch?v=lTRiuFIWV54",
    ),
    _track(
        "Quiet Library",
        "Chillhop Music",
        "lofi",
        ["focus", "study", "calm"],
        72,
        "https://www.youtube.com/watch?v=5qap5aO4i9A",
    ),
    _track(
        "Paperback Dreams",
        "Pueblo Vista",
        "lofi",
        ["dream", "study", "calm"],
        70,
        "https://www.youtube.com/watch?v=DjS5Dsi8nMY",
    ),
    _track(
        "Afternoon Tea",
        "Lo-Fi Beats",
        "lofi",
        ["calm", "peaceful", "warm"],
        74,
        "https://www.youtube.com/watch?v=7NOSDKb0HlU",
    ),
    _track(
        "Distant Memory",
        "Lofi Girl",
        "lofi",
        ["melancholy", "introspective"],
        72,
        "https://www.youtube.com/watch?v=1fueA5aSVwE",
    ),
    _track(
        "Soft Lamp Light",
        "Dreamy",
        "lofi",
        ["calm", "warm", "introspective"],
        68,
        "https://www.youtube.com/watch?v=tNkZsRW7h2c",
    ),
    _track(
        "Hometown Cafe",
        "Chillhop Music",
        "lofi",
        ["focus", "calm", "study"],
        76,
        "https://www.youtube.com/watch?v=fLexgOxsZu0",
    ),
    _track(
        "Midnight Walk",
        "Lo-Fi Vibes",
        "lofi",
        ["dream", "calm", "atmospheric"],
        70,
        "https://www.youtube.com/watch?v=4xDzrJKXOOY",
    ),
    _track(
        "Cassette Tape Static",
        "Lo-Fi Records",
        "lofi",
        ["warm", "introspective", "calm"],
        74,
        "https://www.youtube.com/watch?v=Ap4dF1K0gm0",
    ),
    _track(
        "Sundown Routine",
        "Pueblo Vista",
        "lofi",
        ["focus", "study", "calm"],
        72,
        "https://www.youtube.com/watch?v=gm_l-gIvVRQ",
    ),
    _track(
        "Blue Hour",
        "Chillhop Music",
        "lofi",
        ["dream", "atmospheric", "calm"],
        70,
        "https://www.youtube.com/watch?v=4xDzrJKXOOY",
    ),
    _track(
        "Slow Burn",
        "Lofi Girl",
        "lofi",
        ["focus", "deep", "study"],
        76,
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    ),
    _track(
        "Notebook Scribbles",
        "Dreamy",
        "lofi",
        ["focus", "calm", "study"],
        72,
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    ),
    _track(
        "Old Polaroids",
        "Lo-Fi Beats",
        "lofi",
        ["melancholy", "warm", "introspective"],
        70,
        "https://www.youtube.com/watch?v=Ap4dF1K0gm0",
    ),
    _track(
        "Hourglass",
        "Chillhop Music",
        "lofi",
        ["calm", "peaceful", "deep"],
        72,
        "https://www.youtube.com/watch?v=lTRiuFIWV54",
    ),
    _track(
        "Headphones On",
        "Lofi Records",
        "lofi",
        ["focus", "study", "introspective"],
        74,
        "https://www.youtube.com/watch?v=8jPQjjsBbIc",
    ),
    _track(
        "Bedroom Glow",
        "Pueblo Vista",
        "lofi",
        ["warm", "calm", "dream"],
        70,
        "https://www.youtube.com/watch?v=DjS5Dsi8nMY",
    ),
    _track(
        "Paper Lanterns",
        "Dreamy",
        "lofi",
        ["calm", "peaceful", "atmospheric"],
        68,
        "https://www.youtube.com/watch?v=7NOSDKb0HlU",
    ),
    _track(
        "Subway Echoes",
        "Lo-Fi Vibes",
        "lofi",
        ["focus", "study", "deep"],
        76,
        "https://www.youtube.com/watch?v=fLexgOxsZu0",
    ),
    _track(
        "Flickering Screen",
        "Chillhop Music",
        "lofi",
        ["calm", "introspective", "warm"],
        72,
        "https://www.youtube.com/watch?v=Ap4dF1K0gm0",
    ),
    _track(
        "Soft Static",
        "Lofi Girl",
        "lofi",
        ["atmospheric", "dream", "calm"],
        70,
        "https://www.youtube.com/watch?v=1fueA5aSVwE",
    ),
    _track(
        "Reading Glasses",
        "Lo-Fi Beats",
        "lofi",
        ["focus", "study", "peaceful"],
        74,
        "https://www.youtube.com/watch?v=5qap5aO4i9A",
    ),
    _track(
        "Slow Motion Drift",
        "Pueblo Vista",
        "lofi",
        ["dream", "calm", "atmospheric"],
        72,
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    ),
    _track(
        "Indie Cafe Mornings",
        "Chillhop Music",
        "lofi",
        ["bright", "focus", "uplifting"],
        80,
        "https://www.youtube.com/watch?v=gm_l-gIvVRQ",
    ),
    _track(
        "Pencil Shavings",
        "Dreamy",
        "lofi",
        ["focus", "study", "calm"],
        70,
        "https://www.youtube.com/watch?v=tNkZsRW7h2c",
    ),
    _track(
        "Soft Tones",
        "Lo-Fi Vibes",
        "lofi",
        ["calm", "peaceful", "warm"],
        72,
        "https://www.youtube.com/watch?v=oPVteJElF4o",
    ),
    _track(
        "Comfort Zone",
        "Lofi Records",
        "lofi",
        ["warm", "introspective", "calm"],
        76,
        "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    ),
    _track(
        "Out of Focus",
        "Chillhop Music",
        "lofi",
        ["focus", "study", "deep"],
        70,
        "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    ),
    _track(
        "Slow Heart",
        "Lo-Fi Beats",
        "lofi",
        ["melancholy", "warm", "calm"],
        68,
        "https://www.youtube.com/watch?v=M8bDpHXNcCQ",
    ),
    _track(
        "Library Floor",
        "Pueblo Vista",
        "lofi",
        ["focus", "study", "peaceful"],
        74,
        "https://www.youtube.com/watch?v=fLexgOxsZu0",
    ),
    _track(
        "Afternoon Sun",
        "Dreamy",
        "lofi",
        ["bright", "warm", "calm"],
        78,
        "https://www.youtube.com/watch?v=gm_l-gIvVRQ",
    ),
    _track(
        "Soft Pulse",
        "Lofi Girl",
        "lofi",
        ["focus", "calm", "deep"],
        72,
        "https://www.youtube.com/watch?v=8jPQjjsBbIc",
    ),
    _track(
        "Yellow Lamp",
        "Chillhop Music",
        "lofi",
        ["warm", "introspective"],
        70,
        "https://www.youtube.com/watch?v=DjS5Dsi8nMY",
    ),
    _track(
        "Tape Hiss",
        "Lo-Fi Vibes",
        "lofi",
        ["warm", "atmospheric", "calm"],
        74,
        "https://www.youtube.com/watch?v=1fueA5aSVwE",
    ),
    _track(
        "Easy Sunday",
        "Lo-Fi Records",
        "lofi",
        ["bright", "relaxing", "calm"],
        80,
        "https://www.youtube.com/watch?v=lTRiuFIWV54",
    ),
    _track(
        "Pillow Talk",
        "Pueblo Vista",
        "lofi",
        ["dream", "warm", "introspective"],
        70,
        "https://www.youtube.com/watch?v=Ap4dF1K0gm0",
    ),
    _track(
        "Soft Walk",
        "Dreamy",
        "lofi",
        ["calm", "peaceful", "atmospheric"],
        72,
        "https://www.youtube.com/watch?v=7NOSDKb0HlU",
    ),
    _track(
        "Window Frost",
        "Chillhop Music",
        "lofi",
        ["calm", "dream", "atmospheric"],
        68,
        "https://www.youtube.com/watch?v=OPf0YbXqDm0",
    ),
    _track(
        "Cozy Sweater",
        "Lo-Fi Beats",
        "lofi",
        ["warm", "introspective", "calm"],
        76,
        "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    ),
]


# ---------------------------------------------------------------------------
# Cinematic / Orchestral (40)
# ---------------------------------------------------------------------------
CINEMATIC: list[dict[str, Any]] = [
    _track(
        "Adagio for Strings",
        "Kevin MacLeod",
        "cinematic",
        ["deep", "melancholy", "atmospheric"],
        60,
        "https://freepd.com/music/Adagio%20for%20Strings.mp3",
    ),
    _track(
        "Awkward Meeting",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "introspective"],
        80,
        "https://freepd.com/music/Awkward%20Meeting.mp3",
    ),
    _track(
        "Long Note Four",
        "Kevin MacLeod",
        "cinematic",
        ["peaceful", "calm", "deep"],
        70,
        "https://freepd.com/music/Long%20Note%20Four.mp3",
    ),
    _track(
        "Calm and Peaceful",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "peaceful", "meditative"],
        72,
        "https://freepd.com/music/Calm%20and%20Peaceful.mp3",
    ),
    _track(
        "Meditation Impromptu 02",
        "Kevin MacLeod",
        "cinematic",
        ["meditative", "calm", "deep"],
        60,
        "https://freepd.com/music/Meditation%20Impromptu%2002.mp3",
    ),
    _track(
        "Floating",
        "Tobias Voigt",
        "cinematic",
        ["calm", "atmospheric", "peaceful"],
        72,
        "https://freepd.com/music/Floating.mp3",
    ),
    _track(
        "Hidden Past",
        "Komiku",
        "cinematic",
        ["melancholy", "introspective"],
        76,
        "https://freepd.com/music/Hidden%20Past.mp3",
    ),
    _track(
        "I Can Feel It Coming",
        "Kevin MacLeod",
        "cinematic",
        ["uplifting", "bright", "hopeful"],
        90,
        "https://freepd.com/music/I%20Can%20Feel%20It%20Coming.mp3",
    ),
    _track(
        "Acoustic Breeze",
        "Kevin MacLeod",
        "cinematic",
        ["bright", "uplifting", "peaceful"],
        100,
        "https://freepd.com/music/Acoustic%20Breeze.mp3",
    ),
    _track(
        "Bittersweet",
        "Kevin MacLeod",
        "cinematic",
        ["melancholy", "introspective"],
        80,
        "https://freepd.com/music/Bittersweet.mp3",
    ),
    _track(
        "Discovery",
        "Kevin MacLeod",
        "cinematic",
        ["uplifting", "bright", "hopeful"],
        100,
        "https://freepd.com/music/Discovery.mp3",
    ),
    _track(
        "Inspirational",
        "Kevin MacLeod",
        "cinematic",
        ["uplifting", "hopeful", "bright"],
        90,
        "https://freepd.com/music/Inspirational.mp3",
    ),
    _track(
        "Sunny",
        "Kevin MacLeod",
        "cinematic",
        ["bright", "uplifting", "warm"],
        110,
        "https://freepd.com/music/Sunny.mp3",
    ),
    _track(
        "Wallpaper",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "peaceful", "atmospheric"],
        80,
        "https://freepd.com/music/Wallpaper.mp3",
    ),
    _track(
        "Achaidh Cheide",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "peaceful", "deep"],
        72,
        "https://freepd.com/music/Achaidh%20Cheide.mp3",
    ),
    _track(
        "Anxiety",
        "Kevin MacLeod",
        "cinematic",
        ["deep", "intense", "atmospheric"],
        90,
        "https://freepd.com/music/Anxiety.mp3",
    ),
    _track(
        "Aspirations",
        "Kevin MacLeod",
        "cinematic",
        ["uplifting", "hopeful", "bright"],
        100,
        "https://freepd.com/music/Aspirations.mp3",
    ),
    _track(
        "At Rest",
        "Kevin MacLeod",
        "cinematic",
        ["peaceful", "calm", "meditative"],
        60,
        "https://freepd.com/music/At%20Rest.mp3",
    ),
    _track(
        "Autumn Day",
        "Kevin MacLeod",
        "cinematic",
        ["warm", "calm", "introspective"],
        80,
        "https://freepd.com/music/Autumn%20Day.mp3",
    ),
    _track(
        "Bittersweet Embers",
        "Kevin MacLeod",
        "cinematic",
        ["melancholy", "warm", "introspective"],
        70,
        "https://freepd.com/music/Bittersweet%20Embers.mp3",
    ),
    _track(
        "Budding Trees",
        "Kevin MacLeod",
        "cinematic",
        ["peaceful", "bright", "hopeful"],
        80,
        "https://freepd.com/music/Budding%20Trees.mp3",
    ),
    _track(
        "Cylinder Two",
        "Tobias Voigt",
        "cinematic",
        ["atmospheric", "calm", "deep"],
        72,
        "https://freepd.com/music/Cylinder%20Two.mp3",
    ),
    _track(
        "Daylight",
        "Kevin MacLeod",
        "cinematic",
        ["bright", "uplifting", "warm"],
        100,
        "https://freepd.com/music/Daylight.mp3",
    ),
    _track(
        "Deep Haze",
        "Kevin MacLeod",
        "cinematic",
        ["deep", "atmospheric", "calm"],
        70,
        "https://freepd.com/music/Deep%20Haze.mp3",
    ),
    _track(
        "Dvorak Polka",
        "Kevin MacLeod",
        "cinematic",
        ["bright", "uplifting", "peaceful"],
        120,
        "https://freepd.com/music/Dvorak%20Polka.mp3",
    ),
    _track(
        "Evening Fall",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "warm", "peaceful"],
        70,
        "https://freepd.com/music/Evening%20Fall.mp3",
    ),
    _track(
        "Farewell",
        "Kevin MacLeod",
        "cinematic",
        ["melancholy", "deep", "atmospheric"],
        60,
        "https://freepd.com/music/Farewell.mp3",
    ),
    _track(
        "Floating Vibes",
        "Airglow",
        "cinematic",
        ["calm", "atmospheric", "dream"],
        72,
        "https://freepd.com/music/Floating%20Vibes.mp3",
    ),
    _track(
        "Forest of Dreams",
        "Komiku",
        "cinematic",
        ["dream", "atmospheric", "calm"],
        80,
        "https://freepd.com/music/Forest%20of%20Dreams.mp3",
    ),
    _track(
        "Heart of the Beast",
        "Kevin MacLeod",
        "cinematic",
        ["intense", "deep", "atmospheric"],
        100,
        "https://freepd.com/music/Heart%20of%20the%20Beast.mp3",
    ),
    _track(
        "Ice and Snow",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "peaceful", "deep"],
        60,
        "https://freepd.com/music/Ice%20and%20Snow.mp3",
    ),
    _track(
        "Long Note Three",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "peaceful", "deep"],
        70,
        "https://freepd.com/music/Long%20Note%20Three.mp3",
    ),
    _track(
        "Onward to Glory",
        "Kevin MacLeod",
        "cinematic",
        ["uplifting", "hopeful", "intense"],
        100,
        "https://freepd.com/music/Onward%20to%20Glory.mp3",
    ),
    _track(
        "Painting Room",
        "Scott Buckley",
        "cinematic",
        ["calm", "peaceful", "atmospheric"],
        72,
        "https://freepd.com/music/Painting%20Room.mp3",
    ),
    _track(
        "Promise",
        "Kevin MacLeod",
        "cinematic",
        ["warm", "hopeful", "uplifting"],
        80,
        "https://freepd.com/music/Promise.mp3",
    ),
    _track(
        "Reach for the Sky",
        "Kevin MacLeod",
        "cinematic",
        ["uplifting", "bright", "intense"],
        110,
        "https://freepd.com/music/Reach%20for%20the%20Sky.mp3",
    ),
    _track(
        "Rites",
        "Kevin MacLeod",
        "cinematic",
        ["deep", "atmospheric", "meditative"],
        60,
        "https://freepd.com/music/Rites.mp3",
    ),
    _track(
        "Snowfall",
        "Øneheart & Reidenshi",
        "cinematic",
        ["dream", "calm", "atmospheric"],
        72,
        "https://freepd.com/music/Snowfall.mp3",
    ),
    _track(
        "Starlight",
        "Kevin MacLeod",
        "cinematic",
        ["calm", "dream", "peaceful"],
        70,
        "https://freepd.com/music/Starlight.mp3",
    ),
    _track(
        "Touching Moment",
        "Kevin MacLeod",
        "cinematic",
        ["warm", "introspective", "hopeful"],
        80,
        "https://freepd.com/music/Touching%20Moment.mp3",
    ),
]


# ---------------------------------------------------------------------------
# Ambient / Drone (30)
# ---------------------------------------------------------------------------
AMBIENT: list[dict[str, Any]] = [
    _track(
        "Deep Drone Sunrise",
        "Kevin MacLeod",
        "ambient",
        ["deep", "atmospheric", "meditative"],
        None,
        "https://freepd.com/music/Deep%20Drone%20Sunrise.mp3",
    ),
    _track(
        "Almost a Whisper",
        "Kevin MacLeod",
        "ambient",
        ["calm", "peaceful", "meditative"],
        None,
        "https://freepd.com/music/Almost%20a%20Whisper.mp3",
    ),
    _track(
        "Ambient Bed",
        "Kevin MacLeod",
        "ambient",
        ["calm", "atmospheric", "peaceful"],
        None,
        "https://freepd.com/music/Ambient%20Bed.mp3",
    ),
    _track(
        "Ambient Pad",
        "Tobias Voigt",
        "ambient",
        ["calm", "atmospheric", "dream"],
        None,
        "https://freepd.com/music/Ambient%20Pad.mp3",
    ),
    _track(
        "Atmospheric Soundscape 1",
        "Kevin MacLeod",
        "ambient",
        ["atmospheric", "deep", "dream"],
        None,
        "https://freepd.com/music/Atmospheric%20Soundscape%201.mp3",
    ),
    _track(
        "Atmospheric Soundscape 2",
        "Kevin MacLeod",
        "ambient",
        ["atmospheric", "deep", "calm"],
        None,
        "https://freepd.com/music/Atmospheric%20Soundscape%202.mp3",
    ),
    _track(
        "Calm Before the Storm",
        "Kevin MacLeod",
        "ambient",
        ["calm", "deep", "atmospheric"],
        None,
        "https://freepd.com/music/Calm%20Before%20the%20Storm.mp3",
    ),
    _track(
        "Crystal Lake",
        "Komiku",
        "ambient",
        ["calm", "peaceful", "dream"],
        None,
        "https://freepd.com/music/Crystal%20Lake.mp3",
    ),
    _track(
        "Deep Blue",
        "Tobias Voigt",
        "ambient",
        ["deep", "calm", "atmospheric"],
        None,
        "https://freepd.com/music/Deep%20Blue.mp3",
    ),
    _track(
        "Dream State",
        "Kevin MacLeod",
        "ambient",
        ["dream", "calm", "atmospheric"],
        None,
        "https://freepd.com/music/Dream%20State.mp3",
    ),
    _track(
        "Drones Rising",
        "Kevin MacLeod",
        "ambient",
        ["deep", "atmospheric", "meditative"],
        None,
        "https://freepd.com/music/Drones%20Rising.mp3",
    ),
    _track(
        "Empty Mind",
        "Kevin MacLeod",
        "ambient",
        ["meditative", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Empty%20Mind.mp3",
    ),
    _track(
        "Endless Space",
        "Tobias Voigt",
        "ambient",
        ["deep", "atmospheric", "dream"],
        None,
        "https://freepd.com/music/Endless%20Space.mp3",
    ),
    _track(
        "Ethereal Relaxation",
        "Kevin MacLeod",
        "ambient",
        ["calm", "peaceful", "dream"],
        None,
        "https://freepd.com/music/Ethereal%20Relaxation.mp3",
    ),
    _track(
        "Floating Abstracts",
        "Kevin MacLeod",
        "ambient",
        ["dream", "atmospheric", "calm"],
        None,
        "https://freepd.com/music/Floating%20Abstracts.mp3",
    ),
    _track(
        "Gentle Ambient",
        "Kevin MacLeod",
        "ambient",
        ["calm", "peaceful", "meditative"],
        None,
        "https://freepd.com/music/Gentle%20Ambient.mp3",
    ),
    _track(
        "Healing",
        "Kevin MacLeod",
        "ambient",
        ["meditative", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Healing.mp3",
    ),
    _track(
        "Inner Peace",
        "Kevin MacLeod",
        "ambient",
        ["meditative", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Inner%20Peace.mp3",
    ),
    _track(
        "Meditation",
        "Kevin MacLeod",
        "ambient",
        ["meditative", "calm", "deep"],
        None,
        "https://freepd.com/music/Meditation.mp3",
    ),
    _track(
        "Night Snow",
        "Tobias Voigt",
        "ambient",
        ["calm", "peaceful", "dream"],
        None,
        "https://freepd.com/music/Night%20Snow.mp3",
    ),
    _track(
        "Outer Reaches",
        "Kevin MacLeod",
        "ambient",
        ["deep", "atmospheric", "dream"],
        None,
        "https://freepd.com/music/Outer%20Reaches.mp3",
    ),
    _track(
        "Peaceful Meditation",
        "Kevin MacLeod",
        "ambient",
        ["meditative", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Peaceful%20Meditation.mp3",
    ),
    _track(
        "Rest",
        "Kevin MacLeod",
        "ambient",
        ["calm", "peaceful", "meditative"],
        None,
        "https://freepd.com/music/Rest.mp3",
    ),
    _track(
        "Sky Above",
        "Kevin MacLeod",
        "ambient",
        ["calm", "atmospheric", "peaceful"],
        None,
        "https://freepd.com/music/Sky%20Above.mp3",
    ),
    _track(
        "Slow Burn Drone",
        "Kevin MacLeod",
        "ambient",
        ["deep", "atmospheric", "meditative"],
        None,
        "https://freepd.com/music/Slow%20Burn%20Drone.mp3",
    ),
    _track(
        "Soft Pillow",
        "Tobias Voigt",
        "ambient",
        ["calm", "peaceful", "dream"],
        None,
        "https://freepd.com/music/Soft%20Pillow.mp3",
    ),
    _track(
        "Starlight Ambient",
        "Kevin MacLeod",
        "ambient",
        ["dream", "calm", "atmospheric"],
        None,
        "https://freepd.com/music/Starlight%20Ambient.mp3",
    ),
    _track(
        "Still",
        "Kevin MacLeod",
        "ambient",
        ["meditative", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Still.mp3",
    ),
    _track(
        "Tender",
        "Kevin MacLeod",
        "ambient",
        ["calm", "warm", "peaceful"],
        None,
        "https://freepd.com/music/Tender.mp3",
    ),
    _track(
        "Underwater",
        "Kevin MacLeod",
        "ambient",
        ["deep", "calm", "dream"],
        None,
        "https://freepd.com/music/Underwater.mp3",
    ),
]


# ---------------------------------------------------------------------------
# Nature Sounds (20)
# ---------------------------------------------------------------------------
NATURE: list[dict[str, Any]] = [
    _track(
        "Forest Rain",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Forest%20Rain.mp3",
    ),
    _track(
        "Mountain Stream",
        "Nature Sounds",
        "nature",
        ["natural", "peaceful", "calm"],
        None,
        "https://freepd.com/music/Mountain%20Stream.mp3",
    ),
    _track(
        "Ocean Waves",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Ocean%20Waves.mp3",
    ),
    _track(
        "Thunderstorm",
        "Nature Sounds",
        "nature",
        ["natural", "deep", "calm"],
        None,
        "https://freepd.com/music/Thunderstorm.mp3",
    ),
    _track(
        "Birds at Dawn",
        "Nature Sounds",
        "nature",
        ["natural", "bright", "peaceful"],
        None,
        "https://freepd.com/music/Birds%20at%20Dawn.mp3",
    ),
    _track(
        "Crackling Fire",
        "Nature Sounds",
        "nature",
        ["natural", "warm", "calm"],
        None,
        "https://freepd.com/music/Crackling%20Fire.mp3",
    ),
    _track(
        "Crickets at Night",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Crickets%20at%20Night.mp3",
    ),
    _track(
        "Gentle Stream",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Gentle%20Stream.mp3",
    ),
    _track(
        "Jungle Ambience",
        "Nature Sounds",
        "nature",
        ["natural", "deep", "calm"],
        None,
        "https://freepd.com/music/Jungle%20Ambience.mp3",
    ),
    _track(
        "Light Rain",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Light%20Rain.mp3",
    ),
    _track(
        "Nighttime Forest",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Nighttime%20Forest.mp3",
    ),
    _track(
        "Ocean Surf",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Ocean%20Surf.mp3",
    ),
    _track(
        "Pine Forest Wind",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Pine%20Forest%20Wind.mp3",
    ),
    _track(
        "Rain on Roof",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Rain%20on%20Roof.mp3",
    ),
    _track(
        "River Current",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/River%20Current.mp3",
    ),
    _track(
        "Snowfall Ambience",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Snowfall%20Ambience.mp3",
    ),
    _track(
        "Spring Birdsong",
        "Nature Sounds",
        "nature",
        ["natural", "bright", "peaceful"],
        None,
        "https://freepd.com/music/Spring%20Birdsong.mp3",
    ),
    _track(
        "Summer Storm",
        "Nature Sounds",
        "nature",
        ["natural", "deep", "atmospheric"],
        None,
        "https://freepd.com/music/Summer%20Storm.mp3",
    ),
    _track(
        "Waterfall",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Waterfall.mp3",
    ),
    _track(
        "Wind in Trees",
        "Nature Sounds",
        "nature",
        ["natural", "calm", "peaceful"],
        None,
        "https://freepd.com/music/Wind%20in%20Trees.mp3",
    ),
]


# ---------------------------------------------------------------------------
# Jazz instrumental (30)
# ---------------------------------------------------------------------------
JAZZ: list[dict[str, Any]] = [
    _track(
        "Smooth Cafe",
        "Bensound",
        "jazz",
        ["smooth", "warm", "calm"],
        90,
        "https://www.bensound.com/royalty-free-music/track/smooth-cafe",
    ),
    _track(
        "Jazz Comedy",
        "Bensound",
        "jazz",
        ["smooth", "bright", "uplifting"],
        110,
        "https://www.bensound.com/royalty-free-music/track/jazz-comedy",
    ),
    _track(
        "Jazzy Frenchy",
        "Bensound",
        "jazz",
        ["smooth", "warm", "introspective"],
        100,
        "https://www.bensound.com/royalty-free-music/track/jazzy-frenchy",
    ),
    _track(
        "Sunday Lounge",
        "Bensound",
        "jazz",
        ["smooth", "relaxing", "warm"],
        85,
        "https://www.bensound.com/royalty-free-music/track/sunday-lounge",
    ),
    _track(
        "Lounge Piano",
        "Bensound",
        "jazz",
        ["smooth", "calm", "warm"],
        80,
        "https://www.bensound.com/royalty-free-music/track/lounge-piano",
    ),
    _track(
        "All That",
        "Bensound",
        "jazz",
        ["smooth", "bright", "uplifting"],
        100,
        "https://www.bensound.com/royalty-free-music/track/all-that",
    ),
    _track(
        "Love Story",
        "Bensound",
        "jazz",
        ["smooth", "warm", "introspective"],
        90,
        "https://www.bensound.com/royalty-free-music/track/love-story",
    ),
    _track(
        "Cute",
        "Bensound",
        "jazz",
        ["bright", "smooth", "uplifting"],
        110,
        "https://www.bensound.com/royalty-free-music/track/cute",
    ),
    _track(
        "Little Idea",
        "Bensound",
        "jazz",
        ["smooth", "bright", "uplifting"],
        120,
        "https://www.bensound.com/royalty-free-music/track/little-idea",
    ),
    _track(
        "Bad Blood",
        "Bensound",
        "jazz",
        ["intense", "smooth", "deep"],
        100,
        "https://www.bensound.com/royalty-free-music/track/bad-blood",
    ),
    _track(
        "Brazz",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "uplifting"],
        110,
        "https://freepd.com/music/Brazz.mp3",
    ),
    _track(
        "Cool Vibes",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "calm", "warm"],
        95,
        "https://freepd.com/music/Cool%20Vibes.mp3",
    ),
    _track(
        "Cute Toy",
        "Kevin MacLeod",
        "jazz",
        ["bright", "smooth", "uplifting"],
        110,
        "https://freepd.com/music/Cute%20Toy.mp3",
    ),
    _track(
        "Dixieland",
        "Kevin MacLeod",
        "jazz",
        ["bright", "uplifting", "warm"],
        130,
        "https://freepd.com/music/Dixieland.mp3",
    ),
    _track(
        "Funkorama",
        "Kevin MacLeod",
        "jazz",
        ["intense", "smooth", "uplifting"],
        120,
        "https://freepd.com/music/Funkorama.mp3",
    ),
    _track(
        "Happy Boy Theme",
        "Kevin MacLeod",
        "jazz",
        ["bright", "uplifting", "smooth"],
        110,
        "https://freepd.com/music/Happy%20Boy%20Theme.mp3",
    ),
    _track(
        "Honey Bee",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "bright"],
        100,
        "https://freepd.com/music/Honey%20Bee.mp3",
    ),
    _track(
        "Jazz in Paris",
        "Benjamin Tissot",
        "jazz",
        ["smooth", "warm", "introspective"],
        100,
        "https://www.bensound.com/royalty-free-music/track/jazz-in-paris",
    ),
    _track(
        "Jingle Bells Swing",
        "Kevin MacLeod",
        "jazz",
        ["bright", "smooth", "uplifting"],
        140,
        "https://freepd.com/music/Jingle%20Bells%20Swing.mp3",
    ),
    _track(
        "Minor Swing",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "bright", "uplifting"],
        130,
        "https://freepd.com/music/Minor%20Swing.mp3",
    ),
    _track(
        "New Frontiers",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "uplifting"],
        100,
        "https://freepd.com/music/New%20Frontiers.mp3",
    ),
    _track(
        "Punk Rock Gone Wrong",
        "Kevin MacLeod",
        "jazz",
        ["intense", "smooth", "bright"],
        120,
        "https://freepd.com/music/Punk%20Rock%20Gone%20Wrong.mp3",
    ),
    _track(
        "Swing Cheese",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "bright", "uplifting"],
        120,
        "https://freepd.com/music/Swing%20Cheese.mp3",
    ),
    _track(
        "Take a Walk",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "calm"],
        100,
        "https://freepd.com/music/Take%20a%20Walk.mp3",
    ),
    _track(
        "Tea for Two",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "introspective"],
        90,
        "https://freepd.com/music/Tea%20for%20Two.mp3",
    ),
    _track(
        "The Elevator Bossa Nova",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "calm"],
        100,
        "https://freepd.com/music/The%20Elevator%20Bossa%20Nova.mp3",
    ),
    _track(
        "The Entertainer",
        "Scott Joplin",
        "jazz",
        ["bright", "uplifting", "smooth"],
        110,
        "https://freepd.com/music/The%20Entertainer.mp3",
    ),
    _track(
        "Vibin",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "introspective"],
        95,
        "https://freepd.com/music/Vibin.mp3",
    ),
    _track(
        "Whiskey on the Mississippi",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "warm", "calm"],
        90,
        "https://freepd.com/music/Whiskey%20on%20the%20Mississippi.mp3",
    ),
    _track(
        "Yesteryear",
        "Kevin MacLeod",
        "jazz",
        ["smooth", "melancholy", "warm"],
        100,
        "https://freepd.com/music/Yesteryear.mp3",
    ),
]


# ---------------------------------------------------------------------------
# Classical focus (30)
# ---------------------------------------------------------------------------
CLASSICAL: list[dict[str, Any]] = [
    _track(
        "Gymnopédie No. 1",
        "Erik Satie",
        "classical",
        ["calm", "peaceful", "meditative"],
        60,
        "https://freepd.com/music/Gymnopedie%20No.%201.mp3",
    ),
    _track(
        "Gymnopédie No. 2",
        "Erik Satie",
        "classical",
        ["calm", "peaceful", "meditative"],
        60,
        "https://freepd.com/music/Gymnopedie%20No.%202.mp3",
    ),
    _track(
        "Gymnopédie No. 3",
        "Erik Satie",
        "classical",
        ["calm", "peaceful", "meditative"],
        60,
        "https://freepd.com/music/Gymnopedie%20No.%203.mp3",
    ),
    _track(
        "Gnossienne No. 1",
        "Erik Satie",
        "classical",
        ["meditative", "deep", "introspective"],
        50,
        "https://freepd.com/music/Gnossienne%20No.%201.mp3",
    ),
    _track(
        "Gnossienne No. 2",
        "Erik Satie",
        "classical",
        ["meditative", "deep", "introspective"],
        50,
        "https://freepd.com/music/Gnossienne%20No.%202.mp3",
    ),
    _track(
        "Gnossienne No. 3",
        "Erik Satie",
        "classical",
        ["meditative", "deep", "introspective"],
        50,
        "https://freepd.com/music/Gnossienne%20No.%203.mp3",
    ),
    _track(
        "Clair de Lune",
        "Claude Debussy",
        "classical",
        ["calm", "peaceful", "dream"],
        60,
        "https://freepd.com/music/Clair%20de%20Lune.mp3",
    ),
    _track(
        "Arabesque No. 1",
        "Claude Debussy",
        "classical",
        ["calm", "peaceful", "bright"],
        80,
        "https://freepd.com/music/Arabesque%20No.%201.mp3",
    ),
    _track(
        "Reverie",
        "Claude Debussy",
        "classical",
        ["dream", "calm", "peaceful"],
        70,
        "https://freepd.com/music/Reverie.mp3",
    ),
    _track(
        "Moonlight Sonata",
        "Ludwig van Beethoven",
        "classical",
        ["calm", "deep", "peaceful"],
        60,
        "https://freepd.com/music/Moonlight%20Sonata.mp3",
    ),
    _track(
        "Für Elise",
        "Ludwig van Beethoven",
        "classical",
        ["calm", "bright", "peaceful"],
        100,
        "https://freepd.com/music/Fur%20Elise.mp3",
    ),
    _track(
        "Pathétique Sonata",
        "Ludwig van Beethoven",
        "classical",
        ["deep", "intense", "melancholy"],
        80,
        "https://freepd.com/music/Pathetique%20Sonata.mp3",
    ),
    _track(
        "Symphony No. 9 - Ode to Joy",
        "Ludwig van Beethoven",
        "classical",
        ["uplifting", "bright", "hopeful"],
        120,
        "https://freepd.com/music/Ode%20to%20Joy.mp3",
    ),
    _track(
        "Nocturne Op. 9 No. 2",
        "Frédéric Chopin",
        "classical",
        ["calm", "peaceful", "melancholy"],
        60,
        "https://freepd.com/music/Nocturne%20Op%209%20No%202.mp3",
    ),
    _track(
        "Nocturne Op. 27 No. 2",
        "Frédéric Chopin",
        "classical",
        ["calm", "peaceful", "melancholy"],
        60,
        "https://freepd.com/music/Nocturne%20Op%2027%20No%202.mp3",
    ),
    _track(
        "Prelude in C Major",
        "Johann Sebastian Bach",
        "classical",
        ["bright", "peaceful", "calm"],
        90,
        "https://freepd.com/music/Prelude%20in%20C%20Major.mp3",
    ),
    _track(
        "Air on the G String",
        "Johann Sebastian Bach",
        "classical",
        ["calm", "peaceful", "warm"],
        70,
        "https://freepd.com/music/Air%20on%20the%20G%20String.mp3",
    ),
    _track(
        "Toccata and Fugue",
        "Johann Sebastian Bach",
        "classical",
        ["intense", "deep", "atmospheric"],
        100,
        "https://freepd.com/music/Toccata%20and%20Fugue.mp3",
    ),
    _track(
        "Canon in D",
        "Johann Pachelbel",
        "classical",
        ["calm", "peaceful", "warm"],
        70,
        "https://freepd.com/music/Canon%20in%20D.mp3",
    ),
    _track(
        "Ave Maria",
        "Franz Schubert",
        "classical",
        ["calm", "peaceful", "deep"],
        70,
        "https://freepd.com/music/Ave%20Maria.mp3",
    ),
    _track(
        "Swan Lake Theme",
        "Pyotr Ilyich Tchaikovsky",
        "classical",
        ["calm", "peaceful", "bright"],
        80,
        "https://freepd.com/music/Swan%20Lake%20Theme.mp3",
    ),
    _track(
        "Nutcracker March",
        "Pyotr Ilyich Tchaikovsky",
        "classical",
        ["uplifting", "bright", "intense"],
        120,
        "https://freepd.com/music/Nutcracker%20March.mp3",
    ),
    _track(
        "Eine Kleine Nachtmusik",
        "Wolfgang Amadeus Mozart",
        "classical",
        ["bright", "uplifting", "peaceful"],
        120,
        "https://freepd.com/music/Eine%20Kleine%20Nachtmusik.mp3",
    ),
    _track(
        "Rondo Alla Turca",
        "Wolfgang Amadeus Mozart",
        "classical",
        ["bright", "uplifting", "intense"],
        120,
        "https://freepd.com/music/Rondo%20Alla%20Turca.mp3",
    ),
    _track(
        "Symphony No. 40",
        "Wolfgang Amadeus Mozart",
        "classical",
        ["intense", "deep", "atmospheric"],
        120,
        "https://freepd.com/music/Symphony%20No%2040.mp3",
    ),
    _track(
        "Hungarian Dance No. 5",
        "Johannes Brahms",
        "classical",
        ["intense", "bright", "uplifting"],
        120,
        "https://freepd.com/music/Hungarian%20Dance%20No%205.mp3",
    ),
    _track(
        "Lullaby (Brahms)",
        "Johannes Brahms",
        "classical",
        ["calm", "peaceful", "warm"],
        70,
        "https://freepd.com/music/Lullaby.mp3",
    ),
    _track(
        "Rhapsody in Blue",
        "George Gershwin",
        "classical",
        ["uplifting", "intense", "bright"],
        130,
        "https://freepd.com/music/Rhapsody%20in%20Blue.mp3",
    ),
    _track(
        "Bolero",
        "Maurice Ravel",
        "classical",
        ["intense", "deep", "atmospheric"],
        70,
        "https://freepd.com/music/Bolero.mp3",
    ),
    _track(
        "Syrinx",
        "Claude Debussy",
        "classical",
        ["calm", "peaceful", "dream"],
        60,
        "https://freepd.com/music/Syrinx.mp3",
    ),
]


# ---------------------------------------------------------------------------
# Synthwave instrumental (30)
# ---------------------------------------------------------------------------
SYNTHWAVE: list[dict[str, Any]] = [
    _track(
        "Neon Drive",
        "Komiku",
        "synthwave",
        ["energetic", "atmospheric", "uplifting"],
        110,
        "https://freepd.com/music/Neon%20Drive.mp3",
    ),
    _track(
        "Nightwave",
        "Tobias Voigt",
        "synthwave",
        ["atmospheric", "dream", "calm"],
        100,
        "https://freepd.com/music/Nightwave.mp3",
    ),
    _track(
        "Midnight Cruise",
        "Komiku",
        "synthwave",
        ["atmospheric", "calm", "dream"],
        105,
        "https://freepd.com/music/Midnight%20Cruise.mp3",
    ),
    _track(
        "Cyber Highway",
        "Tobias Voigt",
        "synthwave",
        ["energetic", "atmospheric", "intense"],
        120,
        "https://freepd.com/music/Cyber%20Highway.mp3",
    ),
    _track(
        "Chrome Sunset",
        "Komiku",
        "synthwave",
        ["warm", "dream", "atmospheric"],
        100,
        "https://freepd.com/music/Chrome%20Sunset.mp3",
    ),
    _track(
        "Retro Arcade",
        "Tobias Voigt",
        "synthwave",
        ["energetic", "bright", "uplifting"],
        120,
        "https://freepd.com/music/Retro%20Arcade.mp3",
    ),
    _track(
        "VHS Dreams",
        "Komiku",
        "synthwave",
        ["dream", "atmospheric", "calm"],
        100,
        "https://freepd.com/music/VHS%20Dreams.mp3",
    ),
    _track(
        "Night City",
        "Tobias Voigt",
        "synthwave",
        ["atmospheric", "deep", "intense"],
        110,
        "https://freepd.com/music/Night%20City.mp3",
    ),
    _track(
        "Crystal Towers",
        "Komiku",
        "synthwave",
        ["bright", "uplifting", "atmospheric"],
        115,
        "https://freepd.com/music/Crystal%20Towers.mp3",
    ),
    _track(
        "Laser Grid",
        "Tobias Voigt",
        "synthwave",
        ["energetic", "atmospheric", "intense"],
        120,
        "https://freepd.com/music/Laser%20Grid.mp3",
    ),
    _track(
        "Mirage",
        "Komiku",
        "synthwave",
        ["dream", "atmospheric", "calm"],
        100,
        "https://freepd.com/music/Mirage.mp3",
    ),
    _track(
        "Outrun",
        "Tobias Voigt",
        "synthwave",
        ["energetic", "uplifting", "atmospheric"],
        120,
        "https://freepd.com/music/Outrun.mp3",
    ),
    _track(
        "Sequencer",
        "Komiku",
        "synthwave",
        ["bright", "energetic", "uplifting"],
        120,
        "https://freepd.com/music/Sequencer.mp3",
    ),
    _track(
        "Tron Lines",
        "Tobias Voigt",
        "synthwave",
        ["atmospheric", "intense", "energetic"],
        115,
        "https://freepd.com/music/Tron%20Lines.mp3",
    ),
    _track(
        "Future Funk",
        "Komiku",
        "synthwave",
        ["bright", "energetic", "uplifting"],
        120,
        "https://freepd.com/music/Future%20Funk.mp3",
    ),
    _track(
        "Digital Love",
        "Tobias Voigt",
        "synthwave",
        ["warm", "dream", "atmospheric"],
        100,
        "https://freepd.com/music/Digital%20Love.mp3",
    ),
    _track(
        "Neon Pulse",
        "Komiku",
        "synthwave",
        ["energetic", "atmospheric", "intense"],
        120,
        "https://freepd.com/music/Neon%20Pulse.mp3",
    ),
    _track(
        "Reactor",
        "Tobias Voigt",
        "synthwave",
        ["intense", "atmospheric", "deep"],
        110,
        "https://freepd.com/music/Reactor.mp3",
    ),
    _track(
        "Stratosphere",
        "Komiku",
        "synthwave",
        ["dream", "atmospheric", "calm"],
        100,
        "https://freepd.com/music/Stratosphere.mp3",
    ),
    _track(
        "Vector Graphics",
        "Tobias Voigt",
        "synthwave",
        ["bright", "energetic", "uplifting"],
        120,
        "https://freepd.com/music/Vector%20Graphics.mp3",
    ),
    _track(
        "Aurora",
        "Komiku",
        "synthwave",
        ["dream", "atmospheric", "calm"],
        100,
        "https://freepd.com/music/Aurora.mp3",
    ),
    _track(
        "Warp Speed",
        "Tobias Voigt",
        "synthwave",
        ["energetic", "intense", "atmospheric"],
        130,
        "https://freepd.com/music/Warp%20Speed.mp3",
    ),
    _track(
        "Night Patrol",
        "Komiku",
        "synthwave",
        ["atmospheric", "deep", "intense"],
        110,
        "https://freepd.com/music/Night%20Patrol.mp3",
    ),
    _track(
        "Glitch",
        "Tobias Voigt",
        "synthwave",
        ["energetic", "bright", "intense"],
        120,
        "https://freepd.com/music/Glitch.mp3",
    ),
    _track(
        "Tokyo Highway",
        "Komiku",
        "synthwave",
        ["energetic", "atmospheric", "uplifting"],
        115,
        "https://freepd.com/music/Tokyo%20Highway.mp3",
    ),
    _track(
        "Spectrum",
        "Tobias Voigt",
        "synthwave",
        ["atmospheric", "dream", "calm"],
        100,
        "https://freepd.com/music/Spectrum.mp3",
    ),
    _track(
        "Synth Runner",
        "Komiku",
        "synthwave",
        ["energetic", "bright", "uplifting"],
        120,
        "https://freepd.com/music/Synth%20Runner.mp3",
    ),
    _track(
        "Memory",
        "Tobias Voigt",
        "synthwave",
        ["melancholy", "atmospheric", "dream"],
        100,
        "https://freepd.com/music/Memory.mp3",
    ),
    _track(
        "Vapor Trail",
        "Komiku",
        "synthwave",
        ["dream", "atmospheric", "calm"],
        100,
        "https://freepd.com/music/Vapor%20Trail.mp3",
    ),
    _track(
        "Hot Pursuit",
        "Tobias Voigt",
        "synthwave",
        ["intense", "energetic", "atmospheric"],
        120,
        "https://freepd.com/music/Hot%20Pursuit.mp3",
    ),
]


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

ALL_SONGS: list[dict[str, Any]] = (
    LOFI + CINEMATIC + AMBIENT + NATURE + JAZZ + CLASSICAL + SYNTHWAVE
)


def build_payload() -> list[dict[str, Any]]:
    """Return the validated song catalog with audio file assignments.
    Only songs whose genre has audio files are included.
    """
    audio_pool: dict[str, list[str]] = {
        g: get_audio_files(g) for g in {s["genre"] for s in ALL_SONGS}
    }
    counters: dict[str, int] = {}
    payload: list[dict[str, Any]] = []
    for song in ALL_SONGS:
        genre = song["genre"]
        files = audio_pool.get(genre, [])
        if not files:
            continue  # skip genres without audio files
        idx = counters.get(genre, 0) % len(files)
        entry = dict(song)
        entry["audio_path"] = f"{genre}/{files[idx]}"
        counters[genre] = idx + 1
        payload.append(entry)
    return payload


def main() -> int:
    output_path = Config.SEEDS_DIR / "songs.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_payload()
    output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False))

    by_genre: dict[str, int] = {}
    for entry in payload:
        by_genre[entry["genre"]] = by_genre.get(entry["genre"], 0) + 1
    print(f"Wrote {len(payload)} songs to {output_path}")
    for genre, count in sorted(by_genre.items()):
        print(f"  {genre:<10} {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
